insertOne via Auto Encryption Client  - keyVault: community server  - target collection: either enterprise or Atlas
TODO: convert to a RS because encrypted index only works with RS.
With queryType being equality,
MDB takes the field as potential index
and the server rejects the incoming connection from an encryption MongoClient.
In this sample, patientId and patientRecord.ssn are the case.
See mongoClient.js - encryptedFieldsMap

Error:
MongoServerError: Encrypted index operations are only supported on replica sets
    at CryptoConnection.onMessage (/home/node/demo/node_modules/mongodb/lib/cmap/connection.js:207:30)
    at MessageStream.<anonymous> (/home/node/demo/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/home/node/demo/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/home/node/demo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28) {
  ok: 0,
  code: 6371602,
  codeName: 'Location6371602',
  [Symbol(errorLabels)]: Set(0) {}
}